# Generated by Django 6.0.7 on 2026-07-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Jarayonda'), ('postponed', 'Kechiktirilgan'), ('delayed', 'Muddatli'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
