# Generated by Django 6.0.7 on 2026-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usta ismi (arxiv)'),
        ),
        migrations.AddField(
            model_name='order',
            name='master_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Usta telefoni (arxiv)'),
        ),
    ]
