# Generated by Django 6.0.7 on 2026-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master_hidden',
            field=models.BooleanField(default=False, verbose_name='Ustadan yashirilgan'),
        ),
    ]
