# Generated by Django 6.0.7 on 2026-07-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_master_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mijoz bahosi'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_review',
            field=models.TextField(blank=True, default='', verbose_name='Mijoz izohi'),
        ),
    ]
