# Generated by Django 6.0.7 on 2026-07-27 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_add_missing_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='Korxona nomi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name="Batafsil ma'lumot")),
                ('image', models.URLField(blank=True, null=True, verbose_name='Rasm')),
                ('phone', models.CharField(max_length=32, verbose_name="Bog'lanish telefoni")),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, default='', max_length=255, verbose_name='Tuman')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_orders', to='categories.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': "Korxona e'loni",
                'verbose_name_plural': "Korxona e'lonlari",
                'db_table': 'enterprise_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
