# Generated by Django 6.0.7 on 2026-07-19 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Usta', 'verbose_name_plural': 'Ustalar'},
        ),
        migrations.AlterField(
            model_name='master',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='master',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='master',
            name='category_id',
            field=models.CharField(max_length=100, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='master',
            name='completed_jobs',
            field=models.IntegerField(default=0, verbose_name='Bajarilgan ishlar'),
        ),
        migrations.AlterField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='master',
            name='district',
            field=models.CharField(max_length=255, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Tajriba (yil)'),
        ),
        migrations.AlterField(
            model_name='master',
            name='extra_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha telefon"),
        ),
        migrations.AlterField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='master',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Onlayn'),
        ),
        migrations.AlterField(
            model_name='master',
            name='monthly_earnings',
            field=models.BigIntegerField(default=0, verbose_name='Oylik daromad'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='master',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='master',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='master',
            name='price_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Narx izohi'),
        ),
        migrations.AlterField(
            model_name='master',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='master',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='master',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Sharhlar soni'),
        ),
        migrations.AlterField(
            model_name='master',
            name='services',
            field=models.TextField(blank=True, null=True, verbose_name='Xizmatlar'),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AlterField(
            model_name='master',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='master',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
    ]
