# Generated by Django 6.0.7 on 2026-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_master_options_alter_master_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
    ]
