# Generated by Django 6.0.7 on 2026-07-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_add_missing_categories'),
        ('masters', '0005_alter_master_category_id_alter_master_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='categories.category', verbose_name='Kategoriya'),
        ),
    ]
