# Generated by Django 6.0.7 on 2026-07-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_master_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='completed_jobs',
        ),
        migrations.RemoveField(
            model_name='master',
            name='monthly_earnings',
        ),
    ]
