# Generated by Django 6.0.7 on 2026-07-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_remove_master_completed_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='phone',
        ),
    ]
