upstream id_passport {
    server 127.0.0.1:8001;
}

server {
    listen 80;
    server_name id.mastergroup.uz;

    client_max_body_size 10M;

    location / {
        include proxy_params;
        proxy_pass http://id_passport;
        proxy_redirect off;
    }
}
