# Generated by Django 6.0.7 on 2026-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20, verbose_name='Daraja')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Manba')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Method')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='Foydalanuvchi ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('data', models.JSONField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Xato log',
                'verbose_name_plural': 'Xato loglari',
                'db_table': 'error_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
