# Generated by Django 6.0.7 on 2026-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('category_id', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
