# Generated by Django 6.0.7 on 2026-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterField(
            model_name='application',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category_id',
            field=models.CharField(max_length=100, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='application',
            name='district',
            field=models.CharField(max_length=255, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Tajriba (yil)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='application',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='application',
            name='services',
            field=models.TextField(blank=True, null=True, verbose_name='Xizmatlar'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('declined', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
