# Generated by Django 6.0.7 on 2026-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_options_alter_application_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='application',
            name='extra_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha telefon"),
        ),
        migrations.AddField(
            model_name='application',
            name='price_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Narx izohi'),
        ),
    ]
