# Generated by Django 6.0.7 on 2026-07-19 15:52

from django.db import migrations, models
import django.db.models.deletion


def populate_user(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    User = apps.get_model('users', 'User')
    for app in Application.objects.all():
        user = User.objects.filter(phone=app.phone).first()
        if user:
            app.user = user
            app.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_avatar_url_application_extra_phone_and_more'),
        ('users', '0004_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.RunPython(populate_user, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.user', verbose_name='Foydalanuvchi'),
        ),
    ]
