# Generated by Django 6.0.7 on 2026-07-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20260719_1552'),
        ('categories', '0003_add_missing_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='categories.category', verbose_name='Kategoriya'),
        ),
    ]
