# Generated by Django 6.0.7 on 2026-07-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_category_id'),
        ('categories', '0003_add_missing_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='categories.category', verbose_name='Kategoriya'),
        ),
    ]
