# Generated by Django 6.0.7 on 2026-07-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_category_id'),
        ('masters', '0006_alter_master_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resulting_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='masters.master', verbose_name='Yaratilgan usta profili'),
        ),
    ]
