# Generated by Django 6.0.7 on 2026-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Kategoriya ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rang')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Rasm')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
