# Generated by Django 6.0.7 on 2026-07-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_master_category_id'),
        ('messages_app', '0003_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='master_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usta ismi (arxiv)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='master_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Usta telefoni (arxiv)'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_as_master', to='masters.master', verbose_name='Usta'),
        ),
    ]
