# Generated by Django 6.0.7 on 2026-07-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_conversation_master_name_conversation_master_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='unread_count',
        ),
        migrations.AddField(
            model_name='conversation',
            name='client_unread',
            field=models.IntegerField(default=0, verbose_name="Mijoz uchun o'qilmagan"),
        ),
        migrations.AddField(
            model_name='conversation',
            name='master_unread',
            field=models.IntegerField(default=0, verbose_name="Usta uchun o'qilmagan"),
        ),
    ]
