# Generated by Django 6.0.7 on 2026-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Reklama', 'verbose_name_plural': 'Reklamalar'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Tariff', 'verbose_name_plural': 'Tarifflar'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='bg_gradient',
            field=models.CharField(max_length=100, verbose_name='Fon gradienti'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='discount',
            field=models.CharField(max_length=50, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Tariff ID'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='months',
            field=models.IntegerField(verbose_name='Oylar'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.BigIntegerField(verbose_name='Narx'),
        ),
    ]
