# Generated by Django 6.0.7 on 2026-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_ad_options_alter_tariff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='Bosishlar soni'),
        ),
    ]
