# Generated by Django 6.0.7 on 2026-07-19 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_master_options_alter_master_avatar_url_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='masters.master', verbose_name='Usta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package_id',
            field=models.CharField(max_length=100, verbose_name='Paket'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Chek rasmi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_text',
            field=models.TextField(blank=True, null=True, verbose_name='Chek matni'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
