"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import subprocess
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')
load_dotenv(BASE_DIR / '.env.prod', override=True)

# Git short SHA of the deployed commit - read once at process start (deploy
# on PythonAnywhere is `git pull` + reload, so a fresh process always means a
# fresh checkout). Used by /api/version so a redeploy is visible without
# anyone hand-bumping a version number.
try:
    GIT_COMMIT_SHA = subprocess.check_output(
        ['git', 'rev-parse', '--short', 'HEAD'], cwd=BASE_DIR, stderr=subprocess.DEVNULL,
    ).decode().strip()
    GIT_COMMIT_DATE = subprocess.check_output(
        ['git', 'log', '-1', '--format=%cd', '--date=format:%Y-%m-%d'], cwd=BASE_DIR, stderr=subprocess.DEVNULL,
    ).decode().strip()
except Exception:
    GIT_COMMIT_SHA = 'dev'
    GIT_COMMIT_DATE = ''


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-8z3k24oo&$prp%^m2!-17bf-m^eq_6ypkj4f2j(k_*p%$pn^_^')

DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Without an explicit config, our own loggers fall back to logging's
# last-resort handler (WARNING+ only, no context). SMS/push failures are
# diagnosed from the PythonAnywhere error log, which is stderr - so send
# app logs there deliberately, with the logger name and timestamp attached.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'app': {'format': '[{asctime}] {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'app'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
}


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'core',
    'users',
    'masters',
    'orders',
    'applications',
    'categories',
    'messages_app',
    'payments',
    'marketplace',
    'enterprise',
    'push_api',
    'push_notifications',
    'site_settings',
    'notifications',
    'error_log',
]

APPEND_SLASH = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # After CorsMiddleware so its 403s still carry CORS headers - otherwise a
    # false positive shows up in the browser as an opaque CORS error instead
    # of the 403 it actually is.
    'core.bot_guard.BotGuardMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.ApiCsrfExemptMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_TYPE = os.getenv('DB_TYPE', 'sqlite')

if DB_TYPE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.getenv('DB_NAME', 'myproject'),
            'USER': os.getenv('DB_USER', 'myprojectuser'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# Django's default cache (no CACHES setting = LocMemCache) is per-process -
# password-reset codes (users/views.py) got set() on whichever worker
# handled the SMS request and were invisible to a different worker handling
# the verify request, so reset silently failed almost every time in
# production. DatabaseCache is shared across every process (and survives a
# worker restart, unlike LocMemCache). Run `manage.py createcachetable`
# after this lands.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.auth.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'error_log': '30/min',
        # Per-IP caps on top of the per-phone limits already in users/views.py -
        # those alone don't stop one client from spraying many different
        # phone numbers (SMS-cost abuse, credential stuffing, API scraping).
        'auth_login': '15/min',
        'auth_register_request': '5/min',
        'auth_register_verify': '20/min',
        'auth_reset_request': '5/min',
        'auth_reset_verify': '20/min',
        'auth_phone_start': '5/min',
        'auth_phone_verify': '20/min',
        # Write caps, per account (per IP when anonymous) - see
        # users.throttling.WriteRateThrottle. GET is never throttled here,
        # so browsing and SEO crawling are unaffected. Sized for a human
        # using the UI, not for a loop: nobody types 30 orders a minute.
        'write_orders': '30/min',
        'write_applications': '40/min',
        'write_messages': '60/min',
        'write_ads': '20/min',
        'write_enterprise': '20/min',
        'write_profile': '20/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'https://mastergroup.uz',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://localhost:8000',
]
CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_SAMESITE = 'Lax'
# A deploy reached over plain HTTP (an IP-only server with no certificate)
# never gets a Secure cookie back from the browser, which locks you out of
# /admin/ even though DEBUG is correctly False. install-server.sh sets
# SECURE_COOKIES=False in that case; otherwise this follows DEBUG.
SECURE_COOKIES = os.getenv(
    'SECURE_COOKIES', str(not DEBUG),
).lower() in ('true', '1', 'yes')
SESSION_COOKIE_SECURE = SECURE_COOKIES
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = SECURE_COOKIES
CSRF_USE_SESSIONS = True
CSRF_TRUSTED_ORIGINS = [
    'https://mastergroup.uz',
    'http://localhost:3000',
    'http://localhost:8000',
]

# The lists above only cover the fixed dev and Vercel frontends. A self-hosted
# deploy also has to trust its own origin or admin login fails the CSRF check
# over HTTPS - install-server.sh knows the domain and passes it in here.
CSRF_TRUSTED_ORIGINS += [
    o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS_EXTRA', '').split(',') if o.strip()
]
CORS_ALLOWED_ORIGINS += [
    o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS_EXTRA', '').split(',') if o.strip()
]

PUSH_NOTIFICATIONS_SETTINGS = {
    # pywebpush accepts a file path here and parses the PEM itself
    # (Vapid.from_file) — passing raw file content instead breaks, since
    # Vapid.from_string() can't handle PEM armor, only bare base64url.
    "WP_PRIVATE_KEY": str(BASE_DIR / 'vapid_private.pem'),
    "WP_CLAIMS": {"sub": "mailto:admin@usta.uz"},
}

# Public half of the VAPID keypair above — served to the frontend via
# /api/push/public-key/ so it isn't hardcoded/duplicated in frontend source.
VAPID_PUBLIC_KEY = os.getenv(
    'VAPID_PUBLIC_KEY',
    'BCWw4dPa5tuiuAkq0c502e2xRReJhzmK46HhJZlquiOezLaRruF5PT6ih_Nb0Eyz6Ra2cxG2t5SkJERAJ1midlk',
)

# Payment-proof review bot - see payments/telegram.py.
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_ADMIN_CHAT_ID = os.getenv('TELEGRAM_ADMIN_CHAT_ID', '')
# Random path segment (not just /api/telegram/webhook/) plus the secret
# token header below - both must match, so guessing the URL alone isn't
# enough to fire fake approve/reject callbacks.
TELEGRAM_WEBHOOK_PATH = os.getenv('TELEGRAM_WEBHOOK_PATH', '')
TELEGRAM_WEBHOOK_SECRET = os.getenv('TELEGRAM_WEBHOOK_SECRET', '')

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "core.storage.LenientManifestStaticFilesStorage",
    },
}

JAZZMIN_SETTINGS = {
    "site_title": "Master Group Admin",
    "site_header": "Master Group",
    "site_brand": "Master Group Admin",
    "site_logo": "admin/logo.jpg",
    "login_logo": "admin/logo.jpg",
    "site_logo_classes": "img-circle",
    "site_icon": "admin/logo.ico",
    "welcome_sign": "Master Group boshqaruv paneliga xush kelibsiz",
    "copyright": "Master Group MCHJ",
    "search_model": ["users.User", "orders.Order", "masters.Master"],

    "custom_css": "admin/login.css",

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["push_notifications"],
    "hide_models": [],
    "order_with_respect_to": [
        "users", "masters", "orders", "applications", "categories",
        "marketplace", "payments", "messages_app", "notifications",
        "site_settings", "error_log", "auth",
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "users.User": "fas fa-user",
        "masters.Master": "fas fa-hard-hat",
        "orders.Order": "fas fa-clipboard-list",
        "applications.Application": "fas fa-file-signature",
        "categories.Category": "fas fa-th-large",
        "messages_app.Conversation": "fas fa-comments",
        "messages_app.Message": "fas fa-comment-dots",
        "messages_app.Ticket": "fas fa-life-ring",
        "messages_app.TicketMessage": "fas fa-comment",
        "payments.Payment": "fas fa-money-check-alt",
        "marketplace.Ad": "fas fa-bullhorn",
        "marketplace.Tariff": "fas fa-tags",
        "site_settings.SiteSettings": "fas fa-cogs",
        "site_settings.SmsTemplate": "fas fa-sms",
        "notifications.Notification": "fas fa-bell",
        "error_log.ErrorLog": "fas fa-bug",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "error_log.ErrorLog": "single",
        "site_settings.SiteSettings": "single",
    },

    "show_ui_builder": False,
    # Safe now that LenientManifestStaticFilesStorage (core/storage.py)
    # tolerates the base template's unconditional {% static
    # 'vendor/bootswatch' %} reference instead of 500ing on it.
    "show_theme_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark navbar-primary",
    "sidebar": "sidebar-dark-primary",
    "accent": "accent-primary",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_flat_style": True,
    "default_theme_mode": "dark",
    "theme": "default",
}
