# Generated by Django 6.0.7 on 2026-07-21 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application_approved', 'Ariza tasdiqlandi'), ('application_declined', 'Ariza rad etildi'), ('order_accepted', 'Buyurtma qabul qilindi'), ('order_completed', 'Buyurtma bajarildi'), ('order_cancelled', 'Buyurtma bekor qilindi'), ('order_postponed', 'Buyurtma kechiktirildi'), ('order_new', 'Yangi buyurtma'), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi"), ('ticket_reply', "Qo'llab-quvvatlash javobi"), ('role_changed', "Rol o'zgartirildi")], max_length=50, verbose_name='Tur')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(blank=True, verbose_name='Matn')),
                ('data', models.JSONField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('is_push_sent', models.BooleanField(default=False, verbose_name='Push yuborilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
