# Generated by Django 6.0.7 on 2026-07-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_approved', 'Ariza tasdiqlandi'), ('application_declined', 'Ariza rad etildi'), ('order_accepted', 'Buyurtma qabul qilindi'), ('order_completed', 'Buyurtma bajarildi'), ('order_cancelled', 'Buyurtma bekor qilindi'), ('order_postponed', 'Buyurtma postpond qilindi'), ('order_delayed', 'Buyurtma muddati uzaytirildi'), ('order_new', 'Yangi buyurtma'), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi"), ('ticket_reply', "Qo'llab-quvvatlash javobi"), ('role_changed', "Rol o'zgartirildi"), ('new_message', 'Yangi xabar')], max_length=50, verbose_name='Tur'),
        ),
    ]
