# Generated by Django 6.0.7 on 2026-07-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('reset_request', 'Parolni tiklash'), ('register', "Ro'yxatdan o'tish"), ('application_approved', 'Hamkorlik arizasi tasdiqlandi')], max_length=100, unique=True, verbose_name='Shablon kaliti')),
                ('body', models.TextField(verbose_name='SMS matni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'SMS shablon',
                'verbose_name_plural': 'SMS shablonlar',
                'db_table': 'sms_templates',
            },
        ),
    ]
