# Generated by Django 6.0.7 on 2026-07-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='moderation_note',
            field=models.TextField(blank=True, null=True, verbose_name='Moderator izohi'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='status',
            field=models.CharField(choices=[('pending', 'Moderatsiyada'), ('in_progress', 'Jarayonda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='key',
            field=models.CharField(choices=[('reset_request', 'Parolni tiklash'), ('register', "Ro'yxatdan o'tish"), ('application_approved', 'Hamkorlik arizasi tasdiqlandi'), ('order_created', 'Buyurtma yaratildi'), ('order_in_progress', 'Buyurtma jarayonda'), ('order_completed', 'Buyurtma bajarildi'), ('payment_approved', "To'lov tasdiqlandi")], max_length=100, unique=True, verbose_name='Shablon kaliti'),
        ),
    ]
