# Generated by Django 6.0.7 on 2026-07-19 18:53

from django.db import migrations


def populate_sms_templates(apps, schema_editor):
    SmsTemplate = apps.get_model('site_settings', 'SmsTemplate')
    templates = [
        {
            'key': 'register',
            'body': "Usta ilovasi platformasiga muvaffaqiyatli ro'yxatdan o'tdingiz. Xush kelibsiz!",
        },
        {
            'key': 'application_approved',
            'body': "Usta ilovasi platformasidan: Hamkorlik arizangiz tasdiqlandi! Endi siz ustalar safiga qo'shildingiz.",
        },
        {
            'key': 'order_created',
            'body': "Usta ilovasi platformasida yangi buyurtma yaratildi. Buyurtma tafsilotlari ilovada ko'rishishingiz mumkin.",
        },
        {
            'key': 'order_in_progress',
            'body': "Usta ilovasi platformasidagi buyurtmangiz ustaning qabul qilishini kutamiz.",
        },
        {
            'key': 'order_completed',
            'body': "Usta ilovasi platformasidagi buyurtmangiz bajarildi. Xizmatni baholang.",
        },
        {
            'key': 'payment_approved',
            'body': "Usta ilovasi platformasidan premium obunangiz faollashtirildi.",
        },
        {
            'key': 'reset_request',
            'body': "Usta ilovasi platformasi hisobingiz uchun parolni tiklash uchun kod: 0000. Kodni hech kimga bermang.",
        },
    ]
    for data in templates:
        SmsTemplate.objects.update_or_create(
            key=data['key'],
            defaults={
                'body': data['body'],
                'is_active': True,
            }
        )


def reverse_populate(apps, schema_editor):
    SmsTemplate = apps.get_model('site_settings', 'SmsTemplate')
    SmsTemplate.objects.filter(key__in=[
        'register',
        'application_approved',
        'order_created',
        'order_in_progress',
        'order_completed',
        'payment_approved',
        'reset_request',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_smstemplate_moderation_note_smstemplate_status_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_sms_templates, reverse_populate),
    ]
