# Generated by Django 6.0.7 on 2026-07-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_populate_initial_sms_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smstemplate',
            name='moderation_note',
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='status',
        ),
    ]
