# Generated by Django 6.0.7 on 2026-07-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_smstemplate_moderation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='platform_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Platforma sozlamalari'),
        ),
    ]
