# Generated by Django 6.0.7 on 2026-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_fix_reset_template_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='key',
            field=models.CharField(choices=[('reset_request', 'Parolni tiklash'), ('register', "Ro'yxatdan o'tish"), ('application_approved', 'Hamkorlik arizasi tasdiqlandi'), ('application_declined', 'Hamkorlik arizasi rad etildi'), ('order_created', 'Buyurtma yaratildi'), ('order_in_progress', 'Buyurtma jarayonda'), ('order_completed', 'Buyurtma bajarildi'), ('order_cancelled', 'Buyurtma bekor qilindi'), ('order_delayed', 'Buyurtma kechiktirildi'), ('order_postponed', 'Buyurtma qoldirildi'), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi")], max_length=100, unique=True, verbose_name='Shablon kaliti'),
        ),
    ]
