# Generated by Django 6.0.7 on 2026-07-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_populate_new_sms_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_background_color',
            field=models.CharField(blank=True, default='#0F172A', help_text='manifest.json → background_color, ilova ochilayotgandagi splash fon', max_length=7, verbose_name='Fon rangi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_description',
            field=models.CharField(blank=True, default="O'zbekistondagi eng yaxshi usta va mutaxassislarni topish platformasi", help_text='manifest.json → description', max_length=255, verbose_name='Ilova tavsifi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_name',
            field=models.CharField(blank=True, default='Usta - Professional Ustalar', help_text='manifest.json → name', max_length=100, verbose_name="Ilova nomi (to'liq)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_short_name',
            field=models.CharField(blank=True, default='Usta', help_text='manifest.json → short_name, bosh ekrandagi belgi ostida', max_length=50, verbose_name='Ilova nomi (qisqa)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_theme_color',
            field=models.CharField(blank=True, default='#1D4ED8', help_text='manifest.json → theme_color, brauzer manzil paneli rangi', max_length=7, verbose_name='Tema rangi'),
        ),
    ]
