# Generated by Django 6.0.7 on 2026-07-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_register_template_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disable_devtools',
            field=models.BooleanField(default=False, help_text="Yoqilsa: F12/o'ng tugma/konsol yorliqlari bloklanadi va DevTools ochilganda ogohlantirish ko'rsatiladi. Faqat production uchun - kod redeploy qilmasdan yoqib/o'chirib bo'ladi.", verbose_name='DevTools/debug taqiqlansin'),
        ),
    ]
