# Generated by Django 6.0.7 on 2026-07-24 09:12

from django.db import migrations, models


def backfill_from_platform_settings(apps, schema_editor):
    # These 5 keys used to live only in the free-form platform_settings blob
    # (written by the in-app admin dashboard's PATCH /api/settings/) - copy
    # any values already set there into the new dedicated fields so nothing
    # an admin configured earlier gets silently reset to the field default.
    SiteSettings = apps.get_model('site_settings', 'SiteSettings')
    for obj in SiteSettings.objects.all():
        ps = obj.platform_settings or {}
        changed = False
        if ps.get('premiumMode') in ('active', 'noactive'):
            obj.premium_mode = ps['premiumMode']
            changed = True
        if ps.get('adminCard'):
            obj.admin_card = ps['adminCard']
            changed = True
        if ps.get('adminCardHolder'):
            obj.admin_card_holder = ps['adminCardHolder']
            changed = True
        if isinstance(ps.get('totalUsers'), int):
            obj.total_users_override = ps['totalUsers']
            changed = True
        if ps.get('logotypePath'):
            obj.logotype_path = ps['logotypePath']
            changed = True
        if changed:
            obj.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_sitesettings_disable_devtools'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_card',
            field=models.CharField(blank=True, default='8600 4923 1122 3344', help_text="Ustalar Premium uchun to'lovni shu kartaga qiladi.", max_length=30, verbose_name="To'lov karta raqami"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_card_holder',
            field=models.CharField(blank=True, default='Usta MCHJ', max_length=100, verbose_name='Karta egasi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logotype_path',
            field=models.CharField(blank=True, default='', help_text='Ilova logotipi (PWA belgisi sifatida ham ishlatiladi). Odatda admin panelidagi "Logo" bo\'limidan yuklanadi - bu yerda faqat ko\'rish/qo\'lda tuzatish uchun.', max_length=500, verbose_name='Logotip URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='premium_mode',
            field=models.CharField(choices=[('active', 'Faol - ustalar Premium sotib olishi mumkin'), ('noactive', "Nofaol - Premium sotib olish o'chirilgan")], default='active', max_length=20, verbose_name='Premium holati'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='total_users_override',
            field=models.PositiveIntegerField(blank=True, help_text='Bosh sahifadagi "N ta faol foydalanuvchi" belgisida shu son ko\'rsatiladi. Bo\'sh qoldirilsa, haqiqiy ro\'yxatdan o\'tgan foydalanuvchilar soni ko\'rsatiladi.', null=True, verbose_name="Foydalanuvchilar soni (ko'rsatiladigan)"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='platform_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha sozlamalar (ixtiyoriy)"),
        ),
        migrations.RunPython(backfill_from_platform_settings, reverse),
    ]
