# Generated by Django 6.0.7 on 2026-07-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_rebrand_usta_to_master_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_card_holder',
            field=models.CharField(blank=True, default='Master Group MCHJ', max_length=100, verbose_name='Karta egasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='manifest_name',
            field=models.CharField(blank=True, default='Master Group - Professional Ustalar', help_text='manifest.json → name', max_length=100, verbose_name="Ilova nomi (to'liq)"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='manifest_short_name',
            field=models.CharField(blank=True, default='Master Group', help_text='manifest.json → short_name, bosh ekrandagi belgi ostida', max_length=50, verbose_name='Ilova nomi (qisqa)'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='key',
            field=models.CharField(choices=[('reset_request', 'Parolni tiklash'), ('register', "Ro'yxatdan o'tish"), ('login', 'Tizimga kirish kodi'), ('application_approved', 'Hamkorlik arizasi tasdiqlandi'), ('application_declined', 'Hamkorlik arizasi rad etildi'), ('order_created', 'Buyurtma yaratildi'), ('order_in_progress', 'Buyurtma jarayonda'), ('order_completed', 'Buyurtma bajarildi'), ('order_cancelled', 'Buyurtma bekor qilindi'), ('order_delayed', 'Buyurtma kechiktirildi'), ('order_postponed', 'Buyurtma qoldirildi'), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi")], max_length=100, unique=True, verbose_name='Shablon kaliti'),
        ),
    ]
