# Generated by Django 6.0.7 on 2026-08-07 07:23

import site_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_alter_sitesettings_admin_card_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_categories',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_categories, help_text='manifest.json → categories, JSON massiv', verbose_name='Kategoriyalar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_dir',
            field=models.CharField(choices=[('ltr', 'ltr'), ('rtl', 'rtl'), ('auto', 'auto')], default='ltr', help_text='manifest.json → dir', max_length=5, verbose_name="Yozuv yo'nalishi"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_display',
            field=models.CharField(choices=[('standalone', 'standalone'), ('fullscreen', 'fullscreen'), ('minimal-ui', 'minimal-ui'), ('browser', 'browser')], default='standalone', help_text='manifest.json → display', max_length=20, verbose_name="Ko'rsatish rejimi"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_display_override',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_display_override, help_text='manifest.json → display_override, JSON massiv', verbose_name="Ko'rsatish rejimlari (override)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_edge_side_panel',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_edge_side_panel, help_text='manifest.json → edge_side_panel, JSON obyekt', verbose_name='Edge side panel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_file_handlers',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_file_handlers, help_text='manifest.json → file_handlers, JSON massiv', verbose_name='Fayl handlerlar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_iarc_rating_id',
            field=models.CharField(blank=True, default='e59e0c31-4994-465e-91f6-b0f016e1d231', help_text='manifest.json → iarc_rating_id', max_length=100, verbose_name='IARC reyting ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_id',
            field=models.CharField(blank=True, default='/', help_text='manifest.json → id', max_length=255, verbose_name='Ilova ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_lang',
            field=models.CharField(blank=True, default='uz', help_text='manifest.json → lang', max_length=10, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_launch_handler',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_launch_handler, help_text='manifest.json → launch_handler, JSON obyekt', verbose_name='Launch handler'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_note_taking',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_note_taking, help_text='manifest.json → note_taking, JSON obyekt', verbose_name='Note taking'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_orientation',
            field=models.CharField(choices=[('any', 'any'), ('portrait', 'portrait'), ('landscape', 'landscape'), ('portrait-primary', 'portrait-primary'), ('portrait-secondary', 'portrait-secondary'), ('landscape-primary', 'landscape-primary'), ('landscape-secondary', 'landscape-secondary')], default='portrait', help_text='manifest.json → orientation', max_length=20, verbose_name='Orientatsiya'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_prefer_related_applications',
            field=models.BooleanField(default=False, help_text='manifest.json → prefer_related_applications', verbose_name="Tegishli ilovalar afzal ko'rilsin"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_protocol_handlers',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_protocol_handlers, help_text='manifest.json → protocol_handlers, JSON massiv', verbose_name='Protokol handlerlar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_related_applications',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_related_applications, help_text='manifest.json → related_applications, JSON massiv', verbose_name='Tegishli ilovalar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_scope',
            field=models.CharField(blank=True, default='/', help_text='manifest.json → scope', max_length=255, verbose_name='Scope'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_screenshots',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_screenshots, help_text='manifest.json → screenshots, JSON massiv', verbose_name='Skrinshotlar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_share_target',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_share_target, help_text='manifest.json → share_target, JSON obyekt', verbose_name='Share target'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_shortcuts',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_shortcuts, help_text='manifest.json → shortcuts, JSON massiv', verbose_name='Yorliqlar (shortcuts)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_start_url',
            field=models.CharField(blank=True, default='/', help_text='manifest.json → start_url', max_length=255, verbose_name='Boshlanish URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_tab_strip',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_tab_strip, help_text='manifest.json → tab_strip, JSON obyekt', verbose_name='Tab strip'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='manifest_widgets',
            field=models.JSONField(blank=True, default=site_settings.models.default_manifest_widgets, help_text='manifest.json → widgets, JSON massiv', verbose_name='Vidjetlar'),
        ),
    ]
