# Generated by Django 6.0.7 on 2026-07-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completed_jobs',
        ),
    ]
