# Generated by Django 6.0.7 on 2026-07-24 18:50
import re

from django.db import migrations


def normalize_phones(apps, schema_editor):
    User = apps.get_model('users', 'User')
    seen = set(User.objects.values_list('phone', flat=True))
    for user in User.objects.all():
        normalized = re.sub(r'\s+', '', user.phone or '')
        if normalized == user.phone:
            continue
        if normalized in seen:
            # Another row already owns the normalized form (duplicate
            # account under two spellings of the same number) - leave this
            # one as-is rather than crash the whole migration on a unique
            # constraint; needs manual merge.
            continue
        seen.discard(user.phone)
        seen.add(normalized)
        user.phone = normalized
        user.save(update_fields=['phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_create_cache_table'),
    ]

    operations = [
        migrations.RunPython(normalize_phones, migrations.RunPython.noop),
    ]
